/*
 * Visma Net API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.13.03.0008
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package no.systema.visma.v1client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import no.systema.visma.v1client.model.DtoValueInt32;
import no.systema.visma.v1client.model.DtoValueNullableDateTime;
import no.systema.visma.v1client.model.DtoValueNullableDecimal;
import no.systema.visma.v1client.model.DtoValueString;

/**
 * This class represents a Allocations for Purchase Receipt Line in PurchaseReceiptEndpoint. Used to add/update data.
 */
@ApiModel(description = "This class represents a Allocations for Purchase Receipt Line in PurchaseReceiptEndpoint. Used to add/update data.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-04-16T15:04:09.234+02:00")
public class AllocationsUpdateDto {
  /**
   * Gets or Sets operation
   */
  public enum OperationEnum {
    INSERT("Insert"),
    
    UPDATE("Update"),
    
    DELETE("Delete");

    private String value;

    OperationEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static OperationEnum fromValue(String text) {
      for (OperationEnum b : OperationEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
  }

  @JsonProperty("operation")
  private OperationEnum operation = null;

  @JsonProperty("lineNbr")
  private DtoValueInt32 lineNbr = null;

  @JsonProperty("location")
  private DtoValueString location = null;

  @JsonProperty("lotSerialNumber")
  private DtoValueString lotSerialNumber = null;

  @JsonProperty("quantity")
  private DtoValueNullableDecimal quantity = null;

  @JsonProperty("uom")
  private DtoValueString uom = null;

  @JsonProperty("expirationDate")
  private DtoValueNullableDateTime expirationDate = null;

  public AllocationsUpdateDto operation(OperationEnum operation) {
    this.operation = operation;
    return this;
  }

   /**
   * Get operation
   * @return operation
  **/
  @ApiModelProperty(value = "")
  public OperationEnum getOperation() {
    return operation;
  }

  public void setOperation(OperationEnum operation) {
    this.operation = operation;
  }

  public AllocationsUpdateDto lineNbr(DtoValueInt32 lineNbr) {
    this.lineNbr = lineNbr;
    return this;
  }

   /**
   * Get lineNbr
   * @return lineNbr
  **/
  @ApiModelProperty(value = "")
  public DtoValueInt32 getLineNbr() {
    return lineNbr;
  }

  public void setLineNbr(DtoValueInt32 lineNbr) {
    this.lineNbr = lineNbr;
  }

  public AllocationsUpdateDto location(DtoValueString location) {
    this.location = location;
    return this;
  }

   /**
   * Get location
   * @return location
  **/
  @ApiModelProperty(value = "")
  public DtoValueString getLocation() {
    return location;
  }

  public void setLocation(DtoValueString location) {
    this.location = location;
  }

  public AllocationsUpdateDto lotSerialNumber(DtoValueString lotSerialNumber) {
    this.lotSerialNumber = lotSerialNumber;
    return this;
  }

   /**
   * Get lotSerialNumber
   * @return lotSerialNumber
  **/
  @ApiModelProperty(value = "")
  public DtoValueString getLotSerialNumber() {
    return lotSerialNumber;
  }

  public void setLotSerialNumber(DtoValueString lotSerialNumber) {
    this.lotSerialNumber = lotSerialNumber;
  }

  public AllocationsUpdateDto quantity(DtoValueNullableDecimal quantity) {
    this.quantity = quantity;
    return this;
  }

   /**
   * Get quantity
   * @return quantity
  **/
  @ApiModelProperty(value = "")
  public DtoValueNullableDecimal getQuantity() {
    return quantity;
  }

  public void setQuantity(DtoValueNullableDecimal quantity) {
    this.quantity = quantity;
  }

  public AllocationsUpdateDto uom(DtoValueString uom) {
    this.uom = uom;
    return this;
  }

   /**
   * Get uom
   * @return uom
  **/
  @ApiModelProperty(value = "")
  public DtoValueString getUom() {
    return uom;
  }

  public void setUom(DtoValueString uom) {
    this.uom = uom;
  }

  public AllocationsUpdateDto expirationDate(DtoValueNullableDateTime expirationDate) {
    this.expirationDate = expirationDate;
    return this;
  }

   /**
   * Get expirationDate
   * @return expirationDate
  **/
  @ApiModelProperty(value = "")
  public DtoValueNullableDateTime getExpirationDate() {
    return expirationDate;
  }

  public void setExpirationDate(DtoValueNullableDateTime expirationDate) {
    this.expirationDate = expirationDate;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AllocationsUpdateDto allocationsUpdateDto = (AllocationsUpdateDto) o;
    return Objects.equals(this.operation, allocationsUpdateDto.operation) &&
        Objects.equals(this.lineNbr, allocationsUpdateDto.lineNbr) &&
        Objects.equals(this.location, allocationsUpdateDto.location) &&
        Objects.equals(this.lotSerialNumber, allocationsUpdateDto.lotSerialNumber) &&
        Objects.equals(this.quantity, allocationsUpdateDto.quantity) &&
        Objects.equals(this.uom, allocationsUpdateDto.uom) &&
        Objects.equals(this.expirationDate, allocationsUpdateDto.expirationDate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(operation, lineNbr, location, lotSerialNumber, quantity, uom, expirationDate);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AllocationsUpdateDto {\n");
    
    sb.append("    operation: ").append(toIndentedString(operation)).append("\n");
    sb.append("    lineNbr: ").append(toIndentedString(lineNbr)).append("\n");
    sb.append("    location: ").append(toIndentedString(location)).append("\n");
    sb.append("    lotSerialNumber: ").append(toIndentedString(lotSerialNumber)).append("\n");
    sb.append("    quantity: ").append(toIndentedString(quantity)).append("\n");
    sb.append("    uom: ").append(toIndentedString(uom)).append("\n");
    sb.append("    expirationDate: ").append(toIndentedString(expirationDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

