/*
 * Visma Net API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.13.03.0008
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package no.systema.visma.v1client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * CustomerContractQueryParameters
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-04-16T15:04:09.234+02:00")
public class CustomerContractQueryParameters {
  @JsonProperty("greaterThanValue")
  private String greaterThanValue = null;

  @JsonProperty("numberToRead")
  private Integer numberToRead = null;

  @JsonProperty("skipRecords")
  private Integer skipRecords = null;

  @JsonProperty("orderBy")
  private String orderBy = null;

  @JsonProperty("lastModifiedDateTime")
  private String lastModifiedDateTime = null;

  @JsonProperty("lastModifiedDateTimeCondition")
  private String lastModifiedDateTimeCondition = null;

  @JsonProperty("contractTemplate")
  private String contractTemplate = null;

  /**
   * Gets or Sets status
   */
  public enum StatusEnum {
    DRAFT("Draft"),
    
    INAPPROVAL("InApproval"),
    
    ACTIVE("Active"),
    
    EXPIRED("Expired"),
    
    CANCELED("Canceled"),
    
    COMPLETED("Completed"),
    
    INUPGRADE("InUpgrade"),
    
    PENDINGACTIVATION("PendingActivation");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StatusEnum fromValue(String text) {
      for (StatusEnum b : StatusEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
  }

  @JsonProperty("status")
  private StatusEnum status = null;

  @JsonProperty("customer")
  private String customer = null;

  @JsonProperty("expandSummary")
  private Boolean expandSummary = null;

  @JsonProperty("expandDetails")
  private Boolean expandDetails = null;

  @JsonProperty("attributes")
  private String attributes = null;

  @JsonProperty("expandAttributes")
  private Boolean expandAttributes = null;

  public CustomerContractQueryParameters greaterThanValue(String greaterThanValue) {
    this.greaterThanValue = greaterThanValue;
    return this;
  }

   /**
   * Get greaterThanValue
   * @return greaterThanValue
  **/
  @ApiModelProperty(value = "")
  public String getGreaterThanValue() {
    return greaterThanValue;
  }

  public void setGreaterThanValue(String greaterThanValue) {
    this.greaterThanValue = greaterThanValue;
  }

  public CustomerContractQueryParameters numberToRead(Integer numberToRead) {
    this.numberToRead = numberToRead;
    return this;
  }

   /**
   * Get numberToRead
   * @return numberToRead
  **/
  @ApiModelProperty(value = "")
  public Integer getNumberToRead() {
    return numberToRead;
  }

  public void setNumberToRead(Integer numberToRead) {
    this.numberToRead = numberToRead;
  }

  public CustomerContractQueryParameters skipRecords(Integer skipRecords) {
    this.skipRecords = skipRecords;
    return this;
  }

   /**
   * Get skipRecords
   * @return skipRecords
  **/
  @ApiModelProperty(value = "")
  public Integer getSkipRecords() {
    return skipRecords;
  }

  public void setSkipRecords(Integer skipRecords) {
    this.skipRecords = skipRecords;
  }

  public CustomerContractQueryParameters orderBy(String orderBy) {
    this.orderBy = orderBy;
    return this;
  }

   /**
   * Get orderBy
   * @return orderBy
  **/
  @ApiModelProperty(value = "")
  public String getOrderBy() {
    return orderBy;
  }

  public void setOrderBy(String orderBy) {
    this.orderBy = orderBy;
  }

  public CustomerContractQueryParameters lastModifiedDateTime(String lastModifiedDateTime) {
    this.lastModifiedDateTime = lastModifiedDateTime;
    return this;
  }

   /**
   * Get lastModifiedDateTime
   * @return lastModifiedDateTime
  **/
  @ApiModelProperty(value = "")
  public String getLastModifiedDateTime() {
    return lastModifiedDateTime;
  }

  public void setLastModifiedDateTime(String lastModifiedDateTime) {
    this.lastModifiedDateTime = lastModifiedDateTime;
  }

  public CustomerContractQueryParameters lastModifiedDateTimeCondition(String lastModifiedDateTimeCondition) {
    this.lastModifiedDateTimeCondition = lastModifiedDateTimeCondition;
    return this;
  }

   /**
   * Get lastModifiedDateTimeCondition
   * @return lastModifiedDateTimeCondition
  **/
  @ApiModelProperty(value = "")
  public String getLastModifiedDateTimeCondition() {
    return lastModifiedDateTimeCondition;
  }

  public void setLastModifiedDateTimeCondition(String lastModifiedDateTimeCondition) {
    this.lastModifiedDateTimeCondition = lastModifiedDateTimeCondition;
  }

  public CustomerContractQueryParameters contractTemplate(String contractTemplate) {
    this.contractTemplate = contractTemplate;
    return this;
  }

   /**
   * Get contractTemplate
   * @return contractTemplate
  **/
  @ApiModelProperty(value = "")
  public String getContractTemplate() {
    return contractTemplate;
  }

  public void setContractTemplate(String contractTemplate) {
    this.contractTemplate = contractTemplate;
  }

  public CustomerContractQueryParameters status(StatusEnum status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(value = "")
  public StatusEnum getStatus() {
    return status;
  }

  public void setStatus(StatusEnum status) {
    this.status = status;
  }

  public CustomerContractQueryParameters customer(String customer) {
    this.customer = customer;
    return this;
  }

   /**
   * Get customer
   * @return customer
  **/
  @ApiModelProperty(value = "")
  public String getCustomer() {
    return customer;
  }

  public void setCustomer(String customer) {
    this.customer = customer;
  }

  public CustomerContractQueryParameters expandSummary(Boolean expandSummary) {
    this.expandSummary = expandSummary;
    return this;
  }

   /**
   * Get expandSummary
   * @return expandSummary
  **/
  @ApiModelProperty(value = "")
  public Boolean isExpandSummary() {
    return expandSummary;
  }

  public void setExpandSummary(Boolean expandSummary) {
    this.expandSummary = expandSummary;
  }

  public CustomerContractQueryParameters expandDetails(Boolean expandDetails) {
    this.expandDetails = expandDetails;
    return this;
  }

   /**
   * Get expandDetails
   * @return expandDetails
  **/
  @ApiModelProperty(value = "")
  public Boolean isExpandDetails() {
    return expandDetails;
  }

  public void setExpandDetails(Boolean expandDetails) {
    this.expandDetails = expandDetails;
  }

  public CustomerContractQueryParameters attributes(String attributes) {
    this.attributes = attributes;
    return this;
  }

   /**
   * Get attributes
   * @return attributes
  **/
  @ApiModelProperty(value = "")
  public String getAttributes() {
    return attributes;
  }

  public void setAttributes(String attributes) {
    this.attributes = attributes;
  }

  public CustomerContractQueryParameters expandAttributes(Boolean expandAttributes) {
    this.expandAttributes = expandAttributes;
    return this;
  }

   /**
   * Get expandAttributes
   * @return expandAttributes
  **/
  @ApiModelProperty(value = "")
  public Boolean isExpandAttributes() {
    return expandAttributes;
  }

  public void setExpandAttributes(Boolean expandAttributes) {
    this.expandAttributes = expandAttributes;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CustomerContractQueryParameters customerContractQueryParameters = (CustomerContractQueryParameters) o;
    return Objects.equals(this.greaterThanValue, customerContractQueryParameters.greaterThanValue) &&
        Objects.equals(this.numberToRead, customerContractQueryParameters.numberToRead) &&
        Objects.equals(this.skipRecords, customerContractQueryParameters.skipRecords) &&
        Objects.equals(this.orderBy, customerContractQueryParameters.orderBy) &&
        Objects.equals(this.lastModifiedDateTime, customerContractQueryParameters.lastModifiedDateTime) &&
        Objects.equals(this.lastModifiedDateTimeCondition, customerContractQueryParameters.lastModifiedDateTimeCondition) &&
        Objects.equals(this.contractTemplate, customerContractQueryParameters.contractTemplate) &&
        Objects.equals(this.status, customerContractQueryParameters.status) &&
        Objects.equals(this.customer, customerContractQueryParameters.customer) &&
        Objects.equals(this.expandSummary, customerContractQueryParameters.expandSummary) &&
        Objects.equals(this.expandDetails, customerContractQueryParameters.expandDetails) &&
        Objects.equals(this.attributes, customerContractQueryParameters.attributes) &&
        Objects.equals(this.expandAttributes, customerContractQueryParameters.expandAttributes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(greaterThanValue, numberToRead, skipRecords, orderBy, lastModifiedDateTime, lastModifiedDateTimeCondition, contractTemplate, status, customer, expandSummary, expandDetails, attributes, expandAttributes);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CustomerContractQueryParameters {\n");
    
    sb.append("    greaterThanValue: ").append(toIndentedString(greaterThanValue)).append("\n");
    sb.append("    numberToRead: ").append(toIndentedString(numberToRead)).append("\n");
    sb.append("    skipRecords: ").append(toIndentedString(skipRecords)).append("\n");
    sb.append("    orderBy: ").append(toIndentedString(orderBy)).append("\n");
    sb.append("    lastModifiedDateTime: ").append(toIndentedString(lastModifiedDateTime)).append("\n");
    sb.append("    lastModifiedDateTimeCondition: ").append(toIndentedString(lastModifiedDateTimeCondition)).append("\n");
    sb.append("    contractTemplate: ").append(toIndentedString(contractTemplate)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    customer: ").append(toIndentedString(customer)).append("\n");
    sb.append("    expandSummary: ").append(toIndentedString(expandSummary)).append("\n");
    sb.append("    expandDetails: ").append(toIndentedString(expandDetails)).append("\n");
    sb.append("    attributes: ").append(toIndentedString(attributes)).append("\n");
    sb.append("    expandAttributes: ").append(toIndentedString(expandAttributes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

