/*
 * Visma Net API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.13.03.0008
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package no.systema.visma.v1client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import no.systema.visma.v1client.model.DtoValueString;
import no.systema.visma.v1client.model.SegmentUpdateDto;

/**
 * DepartmentUpdateBaseDto
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-04-16T15:04:09.234+02:00")
public class DepartmentUpdateBaseDto {
  @JsonProperty("departmentId")
  private String departmentId = null;

  @JsonProperty("description")
  private DtoValueString description = null;

  @JsonProperty("expenseAccount")
  private DtoValueString expenseAccount = null;

  @JsonProperty("expenseSubaccount")
  private List<SegmentUpdateDto> expenseSubaccount = null;

  public DepartmentUpdateBaseDto departmentId(String departmentId) {
    this.departmentId = departmentId;
    return this;
  }

   /**
   * Get departmentId
   * @return departmentId
  **/
  @ApiModelProperty(value = "")
  public String getDepartmentId() {
    return departmentId;
  }

  public void setDepartmentId(String departmentId) {
    this.departmentId = departmentId;
  }

  public DepartmentUpdateBaseDto description(DtoValueString description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(value = "")
  public DtoValueString getDescription() {
    return description;
  }

  public void setDescription(DtoValueString description) {
    this.description = description;
  }

  public DepartmentUpdateBaseDto expenseAccount(DtoValueString expenseAccount) {
    this.expenseAccount = expenseAccount;
    return this;
  }

   /**
   * Get expenseAccount
   * @return expenseAccount
  **/
  @ApiModelProperty(value = "")
  public DtoValueString getExpenseAccount() {
    return expenseAccount;
  }

  public void setExpenseAccount(DtoValueString expenseAccount) {
    this.expenseAccount = expenseAccount;
  }

  public DepartmentUpdateBaseDto expenseSubaccount(List<SegmentUpdateDto> expenseSubaccount) {
    this.expenseSubaccount = expenseSubaccount;
    return this;
  }

  public DepartmentUpdateBaseDto addExpenseSubaccountItem(SegmentUpdateDto expenseSubaccountItem) {
    if (this.expenseSubaccount == null) {
      this.expenseSubaccount = new ArrayList<>();
    }
    this.expenseSubaccount.add(expenseSubaccountItem);
    return this;
  }

   /**
   * Get expenseSubaccount
   * @return expenseSubaccount
  **/
  @ApiModelProperty(value = "")
  public List<SegmentUpdateDto> getExpenseSubaccount() {
    return expenseSubaccount;
  }

  public void setExpenseSubaccount(List<SegmentUpdateDto> expenseSubaccount) {
    this.expenseSubaccount = expenseSubaccount;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DepartmentUpdateBaseDto departmentUpdateBaseDto = (DepartmentUpdateBaseDto) o;
    return Objects.equals(this.departmentId, departmentUpdateBaseDto.departmentId) &&
        Objects.equals(this.description, departmentUpdateBaseDto.description) &&
        Objects.equals(this.expenseAccount, departmentUpdateBaseDto.expenseAccount) &&
        Objects.equals(this.expenseSubaccount, departmentUpdateBaseDto.expenseSubaccount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(departmentId, description, expenseAccount, expenseSubaccount);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DepartmentUpdateBaseDto {\n");
    
    sb.append("    departmentId: ").append(toIndentedString(departmentId)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    expenseAccount: ").append(toIndentedString(expenseAccount)).append("\n");
    sb.append("    expenseSubaccount: ").append(toIndentedString(expenseSubaccount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

