/*
 * Visma Net API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.13.03.0008
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package no.systema.visma.v1client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import no.systema.visma.v1client.model.DtoValueNullableBoolean;
import no.systema.visma.v1client.model.DtoValueNullableInt32;
import no.systema.visma.v1client.model.DtoValueString;

/**
 * This class represent a Discount Detail for Purchase Order in Purchase Order Controller. Used to pass data to server for creating or updating an order
 */
@ApiModel(description = "This class represent a Discount Detail for Purchase Order in Purchase Order Controller. Used to pass data to server for creating or updating an order")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-04-16T15:04:09.234+02:00")
public class DiscountDetailUpdateDto {
  /**
   * Gets or Sets operation
   */
  public enum OperationEnum {
    INSERT("Insert"),
    
    UPDATE("Update"),
    
    DELETE("Delete");

    private String value;

    OperationEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static OperationEnum fromValue(String text) {
      for (OperationEnum b : OperationEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
  }

  @JsonProperty("operation")
  private OperationEnum operation = null;

  @JsonProperty("lineNbr")
  private DtoValueNullableInt32 lineNbr = null;

  @JsonProperty("skipDiscount")
  private DtoValueNullableBoolean skipDiscount = null;

  @JsonProperty("discountCode")
  private DtoValueString discountCode = null;

  @JsonProperty("sequanceID")
  private DtoValueString sequanceID = null;

  public DiscountDetailUpdateDto operation(OperationEnum operation) {
    this.operation = operation;
    return this;
  }

   /**
   * Get operation
   * @return operation
  **/
  @ApiModelProperty(value = "")
  public OperationEnum getOperation() {
    return operation;
  }

  public void setOperation(OperationEnum operation) {
    this.operation = operation;
  }

  public DiscountDetailUpdateDto lineNbr(DtoValueNullableInt32 lineNbr) {
    this.lineNbr = lineNbr;
    return this;
  }

   /**
   * Get lineNbr
   * @return lineNbr
  **/
  @ApiModelProperty(value = "")
  public DtoValueNullableInt32 getLineNbr() {
    return lineNbr;
  }

  public void setLineNbr(DtoValueNullableInt32 lineNbr) {
    this.lineNbr = lineNbr;
  }

  public DiscountDetailUpdateDto skipDiscount(DtoValueNullableBoolean skipDiscount) {
    this.skipDiscount = skipDiscount;
    return this;
  }

   /**
   * Get skipDiscount
   * @return skipDiscount
  **/
  @ApiModelProperty(value = "")
  public DtoValueNullableBoolean getSkipDiscount() {
    return skipDiscount;
  }

  public void setSkipDiscount(DtoValueNullableBoolean skipDiscount) {
    this.skipDiscount = skipDiscount;
  }

  public DiscountDetailUpdateDto discountCode(DtoValueString discountCode) {
    this.discountCode = discountCode;
    return this;
  }

   /**
   * Get discountCode
   * @return discountCode
  **/
  @ApiModelProperty(value = "")
  public DtoValueString getDiscountCode() {
    return discountCode;
  }

  public void setDiscountCode(DtoValueString discountCode) {
    this.discountCode = discountCode;
  }

  public DiscountDetailUpdateDto sequanceID(DtoValueString sequanceID) {
    this.sequanceID = sequanceID;
    return this;
  }

   /**
   * Get sequanceID
   * @return sequanceID
  **/
  @ApiModelProperty(value = "")
  public DtoValueString getSequanceID() {
    return sequanceID;
  }

  public void setSequanceID(DtoValueString sequanceID) {
    this.sequanceID = sequanceID;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DiscountDetailUpdateDto discountDetailUpdateDto = (DiscountDetailUpdateDto) o;
    return Objects.equals(this.operation, discountDetailUpdateDto.operation) &&
        Objects.equals(this.lineNbr, discountDetailUpdateDto.lineNbr) &&
        Objects.equals(this.skipDiscount, discountDetailUpdateDto.skipDiscount) &&
        Objects.equals(this.discountCode, discountDetailUpdateDto.discountCode) &&
        Objects.equals(this.sequanceID, discountDetailUpdateDto.sequanceID);
  }

  @Override
  public int hashCode() {
    return Objects.hash(operation, lineNbr, skipDiscount, discountCode, sequanceID);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DiscountDetailUpdateDto {\n");
    
    sb.append("    operation: ").append(toIndentedString(operation)).append("\n");
    sb.append("    lineNbr: ").append(toIndentedString(lineNbr)).append("\n");
    sb.append("    skipDiscount: ").append(toIndentedString(skipDiscount)).append("\n");
    sb.append("    discountCode: ").append(toIndentedString(discountCode)).append("\n");
    sb.append("    sequanceID: ").append(toIndentedString(sequanceID)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

