/*
 * Visma Net API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.13.03.0008
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package no.systema.visma.v1client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import no.systema.visma.v1client.model.DtoValueCustomerDocumentTypes;
import no.systema.visma.v1client.model.DtoValueInt32;
import no.systema.visma.v1client.model.DtoValueNullableBoolean;
import no.systema.visma.v1client.model.DtoValueNullableDateTime;
import no.systema.visma.v1client.model.DtoValueNullableDecimal;
import no.systema.visma.v1client.model.DtoValueNullableSupplierDocumentType;
import no.systema.visma.v1client.model.DtoValueString;

/**
 * This class represents a Landed Cost Line for Purchase Receipt in PurchaseReceiptController. Used for getting data.
 */
@ApiModel(description = "This class represents a Landed Cost Line for Purchase Receipt in PurchaseReceiptController. Used for getting data.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-04-16T15:04:09.234+02:00")
public class LandedCostUpdateDto {
  /**
   * Gets or Sets operation
   */
  public enum OperationEnum {
    INSERT("Insert"),
    
    UPDATE("Update"),
    
    DELETE("Delete");

    private String value;

    OperationEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static OperationEnum fromValue(String text) {
      for (OperationEnum b : OperationEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
  }

  @JsonProperty("operation")
  private OperationEnum operation = null;

  @JsonProperty("lineNbr")
  private DtoValueInt32 lineNbr = null;

  @JsonProperty("landedCostCode")
  private DtoValueString landedCostCode = null;

  @JsonProperty("description")
  private DtoValueString description = null;

  @JsonProperty("purchaseInvoiceNbr")
  private DtoValueString purchaseInvoiceNbr = null;

  @JsonProperty("supplierId")
  private DtoValueString supplierId = null;

  @JsonProperty("locationId")
  private DtoValueString locationId = null;

  @JsonProperty("apBillDate")
  private DtoValueNullableDateTime apBillDate = null;

  @JsonProperty("currency")
  private DtoValueString currency = null;

  @JsonProperty("amount")
  private DtoValueNullableDecimal amount = null;

  @JsonProperty("taxCategory")
  private DtoValueString taxCategory = null;

  @JsonProperty("terms")
  private DtoValueString terms = null;

  @JsonProperty("inventoryId")
  private DtoValueString inventoryId = null;

  @JsonProperty("apDocType")
  private DtoValueNullableSupplierDocumentType apDocType = null;

  @JsonProperty("apRefNbr")
  private DtoValueString apRefNbr = null;

  @JsonProperty("inDocType")
  private DtoValueCustomerDocumentTypes inDocType = null;

  @JsonProperty("inRefNbr")
  private DtoValueString inRefNbr = null;

  @JsonProperty("postponePurchaseInvoiceCreation")
  private DtoValueNullableBoolean postponePurchaseInvoiceCreation = null;

  public LandedCostUpdateDto operation(OperationEnum operation) {
    this.operation = operation;
    return this;
  }

   /**
   * Get operation
   * @return operation
  **/
  @ApiModelProperty(value = "")
  public OperationEnum getOperation() {
    return operation;
  }

  public void setOperation(OperationEnum operation) {
    this.operation = operation;
  }

  public LandedCostUpdateDto lineNbr(DtoValueInt32 lineNbr) {
    this.lineNbr = lineNbr;
    return this;
  }

   /**
   * Get lineNbr
   * @return lineNbr
  **/
  @ApiModelProperty(value = "")
  public DtoValueInt32 getLineNbr() {
    return lineNbr;
  }

  public void setLineNbr(DtoValueInt32 lineNbr) {
    this.lineNbr = lineNbr;
  }

  public LandedCostUpdateDto landedCostCode(DtoValueString landedCostCode) {
    this.landedCostCode = landedCostCode;
    return this;
  }

   /**
   * Get landedCostCode
   * @return landedCostCode
  **/
  @ApiModelProperty(value = "")
  public DtoValueString getLandedCostCode() {
    return landedCostCode;
  }

  public void setLandedCostCode(DtoValueString landedCostCode) {
    this.landedCostCode = landedCostCode;
  }

  public LandedCostUpdateDto description(DtoValueString description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(value = "")
  public DtoValueString getDescription() {
    return description;
  }

  public void setDescription(DtoValueString description) {
    this.description = description;
  }

  public LandedCostUpdateDto purchaseInvoiceNbr(DtoValueString purchaseInvoiceNbr) {
    this.purchaseInvoiceNbr = purchaseInvoiceNbr;
    return this;
  }

   /**
   * Get purchaseInvoiceNbr
   * @return purchaseInvoiceNbr
  **/
  @ApiModelProperty(value = "")
  public DtoValueString getPurchaseInvoiceNbr() {
    return purchaseInvoiceNbr;
  }

  public void setPurchaseInvoiceNbr(DtoValueString purchaseInvoiceNbr) {
    this.purchaseInvoiceNbr = purchaseInvoiceNbr;
  }

  public LandedCostUpdateDto supplierId(DtoValueString supplierId) {
    this.supplierId = supplierId;
    return this;
  }

   /**
   * Get supplierId
   * @return supplierId
  **/
  @ApiModelProperty(value = "")
  public DtoValueString getSupplierId() {
    return supplierId;
  }

  public void setSupplierId(DtoValueString supplierId) {
    this.supplierId = supplierId;
  }

  public LandedCostUpdateDto locationId(DtoValueString locationId) {
    this.locationId = locationId;
    return this;
  }

   /**
   * Get locationId
   * @return locationId
  **/
  @ApiModelProperty(value = "")
  public DtoValueString getLocationId() {
    return locationId;
  }

  public void setLocationId(DtoValueString locationId) {
    this.locationId = locationId;
  }

  public LandedCostUpdateDto apBillDate(DtoValueNullableDateTime apBillDate) {
    this.apBillDate = apBillDate;
    return this;
  }

   /**
   * Get apBillDate
   * @return apBillDate
  **/
  @ApiModelProperty(value = "")
  public DtoValueNullableDateTime getApBillDate() {
    return apBillDate;
  }

  public void setApBillDate(DtoValueNullableDateTime apBillDate) {
    this.apBillDate = apBillDate;
  }

  public LandedCostUpdateDto currency(DtoValueString currency) {
    this.currency = currency;
    return this;
  }

   /**
   * Get currency
   * @return currency
  **/
  @ApiModelProperty(value = "")
  public DtoValueString getCurrency() {
    return currency;
  }

  public void setCurrency(DtoValueString currency) {
    this.currency = currency;
  }

  public LandedCostUpdateDto amount(DtoValueNullableDecimal amount) {
    this.amount = amount;
    return this;
  }

   /**
   * Get amount
   * @return amount
  **/
  @ApiModelProperty(value = "")
  public DtoValueNullableDecimal getAmount() {
    return amount;
  }

  public void setAmount(DtoValueNullableDecimal amount) {
    this.amount = amount;
  }

  public LandedCostUpdateDto taxCategory(DtoValueString taxCategory) {
    this.taxCategory = taxCategory;
    return this;
  }

   /**
   * Get taxCategory
   * @return taxCategory
  **/
  @ApiModelProperty(value = "")
  public DtoValueString getTaxCategory() {
    return taxCategory;
  }

  public void setTaxCategory(DtoValueString taxCategory) {
    this.taxCategory = taxCategory;
  }

  public LandedCostUpdateDto terms(DtoValueString terms) {
    this.terms = terms;
    return this;
  }

   /**
   * Get terms
   * @return terms
  **/
  @ApiModelProperty(value = "")
  public DtoValueString getTerms() {
    return terms;
  }

  public void setTerms(DtoValueString terms) {
    this.terms = terms;
  }

  public LandedCostUpdateDto inventoryId(DtoValueString inventoryId) {
    this.inventoryId = inventoryId;
    return this;
  }

   /**
   * Get inventoryId
   * @return inventoryId
  **/
  @ApiModelProperty(value = "")
  public DtoValueString getInventoryId() {
    return inventoryId;
  }

  public void setInventoryId(DtoValueString inventoryId) {
    this.inventoryId = inventoryId;
  }

  public LandedCostUpdateDto apDocType(DtoValueNullableSupplierDocumentType apDocType) {
    this.apDocType = apDocType;
    return this;
  }

   /**
   * Get apDocType
   * @return apDocType
  **/
  @ApiModelProperty(value = "")
  public DtoValueNullableSupplierDocumentType getApDocType() {
    return apDocType;
  }

  public void setApDocType(DtoValueNullableSupplierDocumentType apDocType) {
    this.apDocType = apDocType;
  }

  public LandedCostUpdateDto apRefNbr(DtoValueString apRefNbr) {
    this.apRefNbr = apRefNbr;
    return this;
  }

   /**
   * Get apRefNbr
   * @return apRefNbr
  **/
  @ApiModelProperty(value = "")
  public DtoValueString getApRefNbr() {
    return apRefNbr;
  }

  public void setApRefNbr(DtoValueString apRefNbr) {
    this.apRefNbr = apRefNbr;
  }

  public LandedCostUpdateDto inDocType(DtoValueCustomerDocumentTypes inDocType) {
    this.inDocType = inDocType;
    return this;
  }

   /**
   * Get inDocType
   * @return inDocType
  **/
  @ApiModelProperty(value = "")
  public DtoValueCustomerDocumentTypes getInDocType() {
    return inDocType;
  }

  public void setInDocType(DtoValueCustomerDocumentTypes inDocType) {
    this.inDocType = inDocType;
  }

  public LandedCostUpdateDto inRefNbr(DtoValueString inRefNbr) {
    this.inRefNbr = inRefNbr;
    return this;
  }

   /**
   * Get inRefNbr
   * @return inRefNbr
  **/
  @ApiModelProperty(value = "")
  public DtoValueString getInRefNbr() {
    return inRefNbr;
  }

  public void setInRefNbr(DtoValueString inRefNbr) {
    this.inRefNbr = inRefNbr;
  }

  public LandedCostUpdateDto postponePurchaseInvoiceCreation(DtoValueNullableBoolean postponePurchaseInvoiceCreation) {
    this.postponePurchaseInvoiceCreation = postponePurchaseInvoiceCreation;
    return this;
  }

   /**
   * Get postponePurchaseInvoiceCreation
   * @return postponePurchaseInvoiceCreation
  **/
  @ApiModelProperty(value = "")
  public DtoValueNullableBoolean getPostponePurchaseInvoiceCreation() {
    return postponePurchaseInvoiceCreation;
  }

  public void setPostponePurchaseInvoiceCreation(DtoValueNullableBoolean postponePurchaseInvoiceCreation) {
    this.postponePurchaseInvoiceCreation = postponePurchaseInvoiceCreation;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LandedCostUpdateDto landedCostUpdateDto = (LandedCostUpdateDto) o;
    return Objects.equals(this.operation, landedCostUpdateDto.operation) &&
        Objects.equals(this.lineNbr, landedCostUpdateDto.lineNbr) &&
        Objects.equals(this.landedCostCode, landedCostUpdateDto.landedCostCode) &&
        Objects.equals(this.description, landedCostUpdateDto.description) &&
        Objects.equals(this.purchaseInvoiceNbr, landedCostUpdateDto.purchaseInvoiceNbr) &&
        Objects.equals(this.supplierId, landedCostUpdateDto.supplierId) &&
        Objects.equals(this.locationId, landedCostUpdateDto.locationId) &&
        Objects.equals(this.apBillDate, landedCostUpdateDto.apBillDate) &&
        Objects.equals(this.currency, landedCostUpdateDto.currency) &&
        Objects.equals(this.amount, landedCostUpdateDto.amount) &&
        Objects.equals(this.taxCategory, landedCostUpdateDto.taxCategory) &&
        Objects.equals(this.terms, landedCostUpdateDto.terms) &&
        Objects.equals(this.inventoryId, landedCostUpdateDto.inventoryId) &&
        Objects.equals(this.apDocType, landedCostUpdateDto.apDocType) &&
        Objects.equals(this.apRefNbr, landedCostUpdateDto.apRefNbr) &&
        Objects.equals(this.inDocType, landedCostUpdateDto.inDocType) &&
        Objects.equals(this.inRefNbr, landedCostUpdateDto.inRefNbr) &&
        Objects.equals(this.postponePurchaseInvoiceCreation, landedCostUpdateDto.postponePurchaseInvoiceCreation);
  }

  @Override
  public int hashCode() {
    return Objects.hash(operation, lineNbr, landedCostCode, description, purchaseInvoiceNbr, supplierId, locationId, apBillDate, currency, amount, taxCategory, terms, inventoryId, apDocType, apRefNbr, inDocType, inRefNbr, postponePurchaseInvoiceCreation);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LandedCostUpdateDto {\n");
    
    sb.append("    operation: ").append(toIndentedString(operation)).append("\n");
    sb.append("    lineNbr: ").append(toIndentedString(lineNbr)).append("\n");
    sb.append("    landedCostCode: ").append(toIndentedString(landedCostCode)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    purchaseInvoiceNbr: ").append(toIndentedString(purchaseInvoiceNbr)).append("\n");
    sb.append("    supplierId: ").append(toIndentedString(supplierId)).append("\n");
    sb.append("    locationId: ").append(toIndentedString(locationId)).append("\n");
    sb.append("    apBillDate: ").append(toIndentedString(apBillDate)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    taxCategory: ").append(toIndentedString(taxCategory)).append("\n");
    sb.append("    terms: ").append(toIndentedString(terms)).append("\n");
    sb.append("    inventoryId: ").append(toIndentedString(inventoryId)).append("\n");
    sb.append("    apDocType: ").append(toIndentedString(apDocType)).append("\n");
    sb.append("    apRefNbr: ").append(toIndentedString(apRefNbr)).append("\n");
    sb.append("    inDocType: ").append(toIndentedString(inDocType)).append("\n");
    sb.append("    inRefNbr: ").append(toIndentedString(inRefNbr)).append("\n");
    sb.append("    postponePurchaseInvoiceCreation: ").append(toIndentedString(postponePurchaseInvoiceCreation)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

