/*
 * Visma Net API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.13.03.0008
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package no.systema.visma.v1client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.LocalDateTime;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import no.systema.visma.v1client.model.AddressDto;
import no.systema.visma.v1client.model.BAccountDescriptionDto;
import no.systema.visma.v1client.model.ContactInfoDto;
import no.systema.visma.v1client.model.VatZoneDto;

/**
 * This class represents a Location in LocationController. Used for getting data.
 */
@ApiModel(description = "This class represents a Location in LocationController. Used for getting data.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-04-16T15:04:09.234+02:00")
public class LocationDto {
  @JsonProperty("baccount")
  private BAccountDescriptionDto baccount = null;

  @JsonProperty("locationId")
  private String locationId = null;

  @JsonProperty("locationName")
  private String locationName = null;

  @JsonProperty("active")
  private Boolean active = null;

  @JsonProperty("address")
  private AddressDto address = null;

  @JsonProperty("contact")
  private ContactInfoDto contact = null;

  @JsonProperty("vatRegistrationId")
  private String vatRegistrationId = null;

  @JsonProperty("vatZone")
  private VatZoneDto vatZone = null;

  @JsonProperty("ediCode")
  private String ediCode = null;

  @JsonProperty("gln")
  private String gln = null;

  @JsonProperty("lastModifieDateTime")
  private LocalDateTime lastModifieDateTime = null;

  @JsonProperty("extras")
  private Map<String, Object> extras = null;

  @JsonProperty("errorInfo")
  private String errorInfo = null;

  public LocationDto baccount(BAccountDescriptionDto baccount) {
    this.baccount = baccount;
    return this;
  }

   /**
   * Get baccount
   * @return baccount
  **/
  @ApiModelProperty(value = "")
  public BAccountDescriptionDto getBaccount() {
    return baccount;
  }

  public void setBaccount(BAccountDescriptionDto baccount) {
    this.baccount = baccount;
  }

  public LocationDto locationId(String locationId) {
    this.locationId = locationId;
    return this;
  }

   /**
   * Get locationId
   * @return locationId
  **/
  @ApiModelProperty(value = "")
  public String getLocationId() {
    return locationId;
  }

  public void setLocationId(String locationId) {
    this.locationId = locationId;
  }

  public LocationDto locationName(String locationName) {
    this.locationName = locationName;
    return this;
  }

   /**
   * Get locationName
   * @return locationName
  **/
  @ApiModelProperty(value = "")
  public String getLocationName() {
    return locationName;
  }

  public void setLocationName(String locationName) {
    this.locationName = locationName;
  }

  public LocationDto active(Boolean active) {
    this.active = active;
    return this;
  }

   /**
   * Get active
   * @return active
  **/
  @ApiModelProperty(value = "")
  public Boolean isActive() {
    return active;
  }

  public void setActive(Boolean active) {
    this.active = active;
  }

  public LocationDto address(AddressDto address) {
    this.address = address;
    return this;
  }

   /**
   * Get address
   * @return address
  **/
  @ApiModelProperty(value = "")
  public AddressDto getAddress() {
    return address;
  }

  public void setAddress(AddressDto address) {
    this.address = address;
  }

  public LocationDto contact(ContactInfoDto contact) {
    this.contact = contact;
    return this;
  }

   /**
   * Get contact
   * @return contact
  **/
  @ApiModelProperty(value = "")
  public ContactInfoDto getContact() {
    return contact;
  }

  public void setContact(ContactInfoDto contact) {
    this.contact = contact;
  }

  public LocationDto vatRegistrationId(String vatRegistrationId) {
    this.vatRegistrationId = vatRegistrationId;
    return this;
  }

   /**
   * Get vatRegistrationId
   * @return vatRegistrationId
  **/
  @ApiModelProperty(value = "")
  public String getVatRegistrationId() {
    return vatRegistrationId;
  }

  public void setVatRegistrationId(String vatRegistrationId) {
    this.vatRegistrationId = vatRegistrationId;
  }

  public LocationDto vatZone(VatZoneDto vatZone) {
    this.vatZone = vatZone;
    return this;
  }

   /**
   * Get vatZone
   * @return vatZone
  **/
  @ApiModelProperty(value = "")
  public VatZoneDto getVatZone() {
    return vatZone;
  }

  public void setVatZone(VatZoneDto vatZone) {
    this.vatZone = vatZone;
  }

  public LocationDto ediCode(String ediCode) {
    this.ediCode = ediCode;
    return this;
  }

   /**
   * Get ediCode
   * @return ediCode
  **/
  @ApiModelProperty(value = "")
  public String getEdiCode() {
    return ediCode;
  }

  public void setEdiCode(String ediCode) {
    this.ediCode = ediCode;
  }

  public LocationDto gln(String gln) {
    this.gln = gln;
    return this;
  }

   /**
   * Get gln
   * @return gln
  **/
  @ApiModelProperty(value = "")
  public String getGln() {
    return gln;
  }

  public void setGln(String gln) {
    this.gln = gln;
  }

  public LocationDto lastModifieDateTime(LocalDateTime lastModifieDateTime) {
    this.lastModifieDateTime = lastModifieDateTime;
    return this;
  }

   /**
   * Get lastModifieDateTime
   * @return lastModifieDateTime
  **/
  @ApiModelProperty(value = "")
  public LocalDateTime getLastModifieDateTime() {
    return lastModifieDateTime;
  }

  public void setLastModifieDateTime(LocalDateTime lastModifieDateTime) {
    this.lastModifieDateTime = lastModifieDateTime;
  }

  public LocationDto extras(Map<String, Object> extras) {
    this.extras = extras;
    return this;
  }

  public LocationDto putExtrasItem(String key, Object extrasItem) {
    if (this.extras == null) {
      this.extras = new HashMap<>();
    }
    this.extras.put(key, extrasItem);
    return this;
  }

   /**
   * Get extras
   * @return extras
  **/
  @ApiModelProperty(value = "")
  public Map<String, Object> getExtras() {
    return extras;
  }

  public void setExtras(Map<String, Object> extras) {
    this.extras = extras;
  }

  public LocationDto errorInfo(String errorInfo) {
    this.errorInfo = errorInfo;
    return this;
  }

   /**
   * Get errorInfo
   * @return errorInfo
  **/
  @ApiModelProperty(value = "")
  public String getErrorInfo() {
    return errorInfo;
  }

  public void setErrorInfo(String errorInfo) {
    this.errorInfo = errorInfo;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LocationDto locationDto = (LocationDto) o;
    return Objects.equals(this.baccount, locationDto.baccount) &&
        Objects.equals(this.locationId, locationDto.locationId) &&
        Objects.equals(this.locationName, locationDto.locationName) &&
        Objects.equals(this.active, locationDto.active) &&
        Objects.equals(this.address, locationDto.address) &&
        Objects.equals(this.contact, locationDto.contact) &&
        Objects.equals(this.vatRegistrationId, locationDto.vatRegistrationId) &&
        Objects.equals(this.vatZone, locationDto.vatZone) &&
        Objects.equals(this.ediCode, locationDto.ediCode) &&
        Objects.equals(this.gln, locationDto.gln) &&
        Objects.equals(this.lastModifieDateTime, locationDto.lastModifieDateTime) &&
        Objects.equals(this.extras, locationDto.extras) &&
        Objects.equals(this.errorInfo, locationDto.errorInfo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(baccount, locationId, locationName, active, address, contact, vatRegistrationId, vatZone, ediCode, gln, lastModifieDateTime, extras, errorInfo);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LocationDto {\n");
    
    sb.append("    baccount: ").append(toIndentedString(baccount)).append("\n");
    sb.append("    locationId: ").append(toIndentedString(locationId)).append("\n");
    sb.append("    locationName: ").append(toIndentedString(locationName)).append("\n");
    sb.append("    active: ").append(toIndentedString(active)).append("\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    contact: ").append(toIndentedString(contact)).append("\n");
    sb.append("    vatRegistrationId: ").append(toIndentedString(vatRegistrationId)).append("\n");
    sb.append("    vatZone: ").append(toIndentedString(vatZone)).append("\n");
    sb.append("    ediCode: ").append(toIndentedString(ediCode)).append("\n");
    sb.append("    gln: ").append(toIndentedString(gln)).append("\n");
    sb.append("    lastModifieDateTime: ").append(toIndentedString(lastModifieDateTime)).append("\n");
    sb.append("    extras: ").append(toIndentedString(extras)).append("\n");
    sb.append("    errorInfo: ").append(toIndentedString(errorInfo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

