/*
 * Visma Net API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.13.03.0008
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package no.systema.visma.v1client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * PackageDetailLineDto
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-04-16T15:04:09.234+02:00")
public class PackageDetailLineDto {
  @JsonProperty("lineNumber")
  private Integer lineNumber = null;

  @JsonProperty("confirmed")
  private Boolean confirmed = null;

  @JsonProperty("boxId")
  private String boxId = null;

  @JsonProperty("type")
  private String type = null;

  @JsonProperty("description")
  private String description = null;

  @JsonProperty("weight")
  private Double weight = null;

  @JsonProperty("uom")
  private String uom = null;

  @JsonProperty("declaredValue")
  private Double declaredValue = null;

  @JsonProperty("coDAmount")
  private Double coDAmount = null;

  @JsonProperty("trackingNumber")
  private String trackingNumber = null;

  @JsonProperty("customRefNbr1")
  private String customRefNbr1 = null;

  @JsonProperty("customRefNbr2")
  private String customRefNbr2 = null;

  public PackageDetailLineDto lineNumber(Integer lineNumber) {
    this.lineNumber = lineNumber;
    return this;
  }

   /**
   * Get lineNumber
   * @return lineNumber
  **/
  @ApiModelProperty(value = "")
  public Integer getLineNumber() {
    return lineNumber;
  }

  public void setLineNumber(Integer lineNumber) {
    this.lineNumber = lineNumber;
  }

  public PackageDetailLineDto confirmed(Boolean confirmed) {
    this.confirmed = confirmed;
    return this;
  }

   /**
   * Get confirmed
   * @return confirmed
  **/
  @ApiModelProperty(value = "")
  public Boolean isConfirmed() {
    return confirmed;
  }

  public void setConfirmed(Boolean confirmed) {
    this.confirmed = confirmed;
  }

  public PackageDetailLineDto boxId(String boxId) {
    this.boxId = boxId;
    return this;
  }

   /**
   * Get boxId
   * @return boxId
  **/
  @ApiModelProperty(value = "")
  public String getBoxId() {
    return boxId;
  }

  public void setBoxId(String boxId) {
    this.boxId = boxId;
  }

  public PackageDetailLineDto type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @ApiModelProperty(value = "")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public PackageDetailLineDto description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(value = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public PackageDetailLineDto weight(Double weight) {
    this.weight = weight;
    return this;
  }

   /**
   * Get weight
   * @return weight
  **/
  @ApiModelProperty(value = "")
  public Double getWeight() {
    return weight;
  }

  public void setWeight(Double weight) {
    this.weight = weight;
  }

  public PackageDetailLineDto uom(String uom) {
    this.uom = uom;
    return this;
  }

   /**
   * Get uom
   * @return uom
  **/
  @ApiModelProperty(value = "")
  public String getUom() {
    return uom;
  }

  public void setUom(String uom) {
    this.uom = uom;
  }

  public PackageDetailLineDto declaredValue(Double declaredValue) {
    this.declaredValue = declaredValue;
    return this;
  }

   /**
   * Get declaredValue
   * @return declaredValue
  **/
  @ApiModelProperty(value = "")
  public Double getDeclaredValue() {
    return declaredValue;
  }

  public void setDeclaredValue(Double declaredValue) {
    this.declaredValue = declaredValue;
  }

  public PackageDetailLineDto coDAmount(Double coDAmount) {
    this.coDAmount = coDAmount;
    return this;
  }

   /**
   * Get coDAmount
   * @return coDAmount
  **/
  @ApiModelProperty(value = "")
  public Double getCoDAmount() {
    return coDAmount;
  }

  public void setCoDAmount(Double coDAmount) {
    this.coDAmount = coDAmount;
  }

  public PackageDetailLineDto trackingNumber(String trackingNumber) {
    this.trackingNumber = trackingNumber;
    return this;
  }

   /**
   * Get trackingNumber
   * @return trackingNumber
  **/
  @ApiModelProperty(value = "")
  public String getTrackingNumber() {
    return trackingNumber;
  }

  public void setTrackingNumber(String trackingNumber) {
    this.trackingNumber = trackingNumber;
  }

  public PackageDetailLineDto customRefNbr1(String customRefNbr1) {
    this.customRefNbr1 = customRefNbr1;
    return this;
  }

   /**
   * Get customRefNbr1
   * @return customRefNbr1
  **/
  @ApiModelProperty(value = "")
  public String getCustomRefNbr1() {
    return customRefNbr1;
  }

  public void setCustomRefNbr1(String customRefNbr1) {
    this.customRefNbr1 = customRefNbr1;
  }

  public PackageDetailLineDto customRefNbr2(String customRefNbr2) {
    this.customRefNbr2 = customRefNbr2;
    return this;
  }

   /**
   * Get customRefNbr2
   * @return customRefNbr2
  **/
  @ApiModelProperty(value = "")
  public String getCustomRefNbr2() {
    return customRefNbr2;
  }

  public void setCustomRefNbr2(String customRefNbr2) {
    this.customRefNbr2 = customRefNbr2;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PackageDetailLineDto packageDetailLineDto = (PackageDetailLineDto) o;
    return Objects.equals(this.lineNumber, packageDetailLineDto.lineNumber) &&
        Objects.equals(this.confirmed, packageDetailLineDto.confirmed) &&
        Objects.equals(this.boxId, packageDetailLineDto.boxId) &&
        Objects.equals(this.type, packageDetailLineDto.type) &&
        Objects.equals(this.description, packageDetailLineDto.description) &&
        Objects.equals(this.weight, packageDetailLineDto.weight) &&
        Objects.equals(this.uom, packageDetailLineDto.uom) &&
        Objects.equals(this.declaredValue, packageDetailLineDto.declaredValue) &&
        Objects.equals(this.coDAmount, packageDetailLineDto.coDAmount) &&
        Objects.equals(this.trackingNumber, packageDetailLineDto.trackingNumber) &&
        Objects.equals(this.customRefNbr1, packageDetailLineDto.customRefNbr1) &&
        Objects.equals(this.customRefNbr2, packageDetailLineDto.customRefNbr2);
  }

  @Override
  public int hashCode() {
    return Objects.hash(lineNumber, confirmed, boxId, type, description, weight, uom, declaredValue, coDAmount, trackingNumber, customRefNbr1, customRefNbr2);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PackageDetailLineDto {\n");
    
    sb.append("    lineNumber: ").append(toIndentedString(lineNumber)).append("\n");
    sb.append("    confirmed: ").append(toIndentedString(confirmed)).append("\n");
    sb.append("    boxId: ").append(toIndentedString(boxId)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    weight: ").append(toIndentedString(weight)).append("\n");
    sb.append("    uom: ").append(toIndentedString(uom)).append("\n");
    sb.append("    declaredValue: ").append(toIndentedString(declaredValue)).append("\n");
    sb.append("    coDAmount: ").append(toIndentedString(coDAmount)).append("\n");
    sb.append("    trackingNumber: ").append(toIndentedString(trackingNumber)).append("\n");
    sb.append("    customRefNbr1: ").append(toIndentedString(customRefNbr1)).append("\n");
    sb.append("    customRefNbr2: ").append(toIndentedString(customRefNbr2)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

