/*
 * Visma Net API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.13.03.0008
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package no.systema.visma.v1client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.LocalDateTime;
import no.systema.visma.v1client.model.RateTableIdDescriptionDto;

/**
 * TaskDto
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-04-16T15:04:09.234+02:00")
public class TaskDto {
  @JsonProperty("taskId")
  private String taskId = null;

  @JsonProperty("description")
  private String description = null;

  @JsonProperty("plannedStart")
  private LocalDateTime plannedStart = null;

  @JsonProperty("plannedEnd")
  private LocalDateTime plannedEnd = null;

  @JsonProperty("startDate")
  private LocalDateTime startDate = null;

  @JsonProperty("rateTable")
  private RateTableIdDescriptionDto rateTable = null;

  /**
   * Gets or Sets status
   */
  public enum StatusEnum {
    PLANNED("Planned"),
    
    ACTIVE("Active"),
    
    COMPLETED("Completed"),
    
    CANCELLED("Cancelled"),
    
    ONHOLD("OnHold"),
    
    PENDINGAPPROVAL("PendingApproval");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StatusEnum fromValue(String text) {
      for (StatusEnum b : StatusEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
  }

  @JsonProperty("status")
  private StatusEnum status = null;

  public TaskDto taskId(String taskId) {
    this.taskId = taskId;
    return this;
  }

   /**
   * Get taskId
   * @return taskId
  **/
  @ApiModelProperty(value = "")
  public String getTaskId() {
    return taskId;
  }

  public void setTaskId(String taskId) {
    this.taskId = taskId;
  }

  public TaskDto description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(value = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public TaskDto plannedStart(LocalDateTime plannedStart) {
    this.plannedStart = plannedStart;
    return this;
  }

   /**
   * Get plannedStart
   * @return plannedStart
  **/
  @ApiModelProperty(value = "")
  public LocalDateTime getPlannedStart() {
    return plannedStart;
  }

  public void setPlannedStart(LocalDateTime plannedStart) {
    this.plannedStart = plannedStart;
  }

  public TaskDto plannedEnd(LocalDateTime plannedEnd) {
    this.plannedEnd = plannedEnd;
    return this;
  }

   /**
   * Get plannedEnd
   * @return plannedEnd
  **/
  @ApiModelProperty(value = "")
  public LocalDateTime getPlannedEnd() {
    return plannedEnd;
  }

  public void setPlannedEnd(LocalDateTime plannedEnd) {
    this.plannedEnd = plannedEnd;
  }

  public TaskDto startDate(LocalDateTime startDate) {
    this.startDate = startDate;
    return this;
  }

   /**
   * Get startDate
   * @return startDate
  **/
  @ApiModelProperty(value = "")
  public LocalDateTime getStartDate() {
    return startDate;
  }

  public void setStartDate(LocalDateTime startDate) {
    this.startDate = startDate;
  }

  public TaskDto rateTable(RateTableIdDescriptionDto rateTable) {
    this.rateTable = rateTable;
    return this;
  }

   /**
   * Get rateTable
   * @return rateTable
  **/
  @ApiModelProperty(value = "")
  public RateTableIdDescriptionDto getRateTable() {
    return rateTable;
  }

  public void setRateTable(RateTableIdDescriptionDto rateTable) {
    this.rateTable = rateTable;
  }

  public TaskDto status(StatusEnum status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(value = "")
  public StatusEnum getStatus() {
    return status;
  }

  public void setStatus(StatusEnum status) {
    this.status = status;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TaskDto taskDto = (TaskDto) o;
    return Objects.equals(this.taskId, taskDto.taskId) &&
        Objects.equals(this.description, taskDto.description) &&
        Objects.equals(this.plannedStart, taskDto.plannedStart) &&
        Objects.equals(this.plannedEnd, taskDto.plannedEnd) &&
        Objects.equals(this.startDate, taskDto.startDate) &&
        Objects.equals(this.rateTable, taskDto.rateTable) &&
        Objects.equals(this.status, taskDto.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(taskId, description, plannedStart, plannedEnd, startDate, rateTable, status);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TaskDto {\n");
    
    sb.append("    taskId: ").append(toIndentedString(taskId)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    plannedStart: ").append(toIndentedString(plannedStart)).append("\n");
    sb.append("    plannedEnd: ").append(toIndentedString(plannedEnd)).append("\n");
    sb.append("    startDate: ").append(toIndentedString(startDate)).append("\n");
    sb.append("    rateTable: ").append(toIndentedString(rateTable)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

