/*
 * Visma Net API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.13.03.0008
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package no.systema.visma.v1client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.LocalDateTime;

/**
 * This class represents a WarehouseDetail part of InventoryItem in InventoryItemController. Used for getting data.
 */
@ApiModel(description = "This class represents a WarehouseDetail part of InventoryItem in InventoryItemController. Used for getting data.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-04-16T15:04:09.234+02:00")
public class WarehouseDetailDto {
  @JsonProperty("isDefault")
  private Boolean isDefault = null;

  @JsonProperty("warehouse")
  private String warehouse = null;

  @JsonProperty("quantityOnHand")
  private Double quantityOnHand = null;

  @JsonProperty("available")
  private Double available = null;

  @JsonProperty("availableForShipment")
  private Double availableForShipment = null;

  @JsonProperty("lastModifiedDateTime")
  private LocalDateTime lastModifiedDateTime = null;

  public WarehouseDetailDto isDefault(Boolean isDefault) {
    this.isDefault = isDefault;
    return this;
  }

   /**
   * Get isDefault
   * @return isDefault
  **/
  @ApiModelProperty(value = "")
  public Boolean isIsDefault() {
    return isDefault;
  }

  public void setIsDefault(Boolean isDefault) {
    this.isDefault = isDefault;
  }

  public WarehouseDetailDto warehouse(String warehouse) {
    this.warehouse = warehouse;
    return this;
  }

   /**
   * Get warehouse
   * @return warehouse
  **/
  @ApiModelProperty(value = "")
  public String getWarehouse() {
    return warehouse;
  }

  public void setWarehouse(String warehouse) {
    this.warehouse = warehouse;
  }

  public WarehouseDetailDto quantityOnHand(Double quantityOnHand) {
    this.quantityOnHand = quantityOnHand;
    return this;
  }

   /**
   * Get quantityOnHand
   * @return quantityOnHand
  **/
  @ApiModelProperty(value = "")
  public Double getQuantityOnHand() {
    return quantityOnHand;
  }

  public void setQuantityOnHand(Double quantityOnHand) {
    this.quantityOnHand = quantityOnHand;
  }

  public WarehouseDetailDto available(Double available) {
    this.available = available;
    return this;
  }

   /**
   * Get available
   * @return available
  **/
  @ApiModelProperty(value = "")
  public Double getAvailable() {
    return available;
  }

  public void setAvailable(Double available) {
    this.available = available;
  }

  public WarehouseDetailDto availableForShipment(Double availableForShipment) {
    this.availableForShipment = availableForShipment;
    return this;
  }

   /**
   * Get availableForShipment
   * @return availableForShipment
  **/
  @ApiModelProperty(value = "")
  public Double getAvailableForShipment() {
    return availableForShipment;
  }

  public void setAvailableForShipment(Double availableForShipment) {
    this.availableForShipment = availableForShipment;
  }

  public WarehouseDetailDto lastModifiedDateTime(LocalDateTime lastModifiedDateTime) {
    this.lastModifiedDateTime = lastModifiedDateTime;
    return this;
  }

   /**
   * Get lastModifiedDateTime
   * @return lastModifiedDateTime
  **/
  @ApiModelProperty(value = "")
  public LocalDateTime getLastModifiedDateTime() {
    return lastModifiedDateTime;
  }

  public void setLastModifiedDateTime(LocalDateTime lastModifiedDateTime) {
    this.lastModifiedDateTime = lastModifiedDateTime;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WarehouseDetailDto warehouseDetailDto = (WarehouseDetailDto) o;
    return Objects.equals(this.isDefault, warehouseDetailDto.isDefault) &&
        Objects.equals(this.warehouse, warehouseDetailDto.warehouse) &&
        Objects.equals(this.quantityOnHand, warehouseDetailDto.quantityOnHand) &&
        Objects.equals(this.available, warehouseDetailDto.available) &&
        Objects.equals(this.availableForShipment, warehouseDetailDto.availableForShipment) &&
        Objects.equals(this.lastModifiedDateTime, warehouseDetailDto.lastModifiedDateTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(isDefault, warehouse, quantityOnHand, available, availableForShipment, lastModifiedDateTime);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WarehouseDetailDto {\n");
    
    sb.append("    isDefault: ").append(toIndentedString(isDefault)).append("\n");
    sb.append("    warehouse: ").append(toIndentedString(warehouse)).append("\n");
    sb.append("    quantityOnHand: ").append(toIndentedString(quantityOnHand)).append("\n");
    sb.append("    available: ").append(toIndentedString(available)).append("\n");
    sb.append("    availableForShipment: ").append(toIndentedString(availableForShipment)).append("\n");
    sb.append("    lastModifiedDateTime: ").append(toIndentedString(lastModifiedDateTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

