/*
 * Visma Net API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.13.03.0008
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package no.systema.visma.v1client.api;

import no.systema.visma.v1client.model.CashAccountDto;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CashAccountApi
 */
@Ignore
public class CashAccountApiTest {

    private final CashAccountApi api = new CashAccountApi();

    
    /**
     * Get all Cash Accounts
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void cashAccountGetAllTest() {
        String greaterThanValue = null;
        Integer numberToRead = null;
        Integer skipRecords = null;
        String lastModifiedDateTime = null;
        String lastModifiedDateTimeCondition = null;
        List<CashAccountDto> response = api.cashAccountGetAll(greaterThanValue, numberToRead, skipRecords, lastModifiedDateTime, lastModifiedDateTimeCondition);

        // TODO: test validations
    }
    
    /**
     * Get a specific cash account
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void cashAccountGetByaccountNumberTest() {
        String accountNumber = null;
        CashAccountDto response = api.cashAccountGetByaccountNumber(accountNumber);

        // TODO: test validations
    }
    
}
