/*
 * Visma Net API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.13.03.0008
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package no.systema.visma.v1client.api;

import no.systema.visma.v1client.model.ContractUsageDto;
import no.systema.visma.v1client.model.ContractUsageUpdateDto;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ContractUsageApi
 */
@Ignore
public class ContractUsageApiTest {

    private final ContractUsageApi api = new ContractUsageApi();

    
    /**
     * Get a range of Contract Usage
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void contractUsageGetAllTest() {
        String greaterThanValue = null;
        Integer numberToRead = null;
        Integer skipRecords = null;
        String lastModifiedDateTime = null;
        String lastModifiedDateTimeCondition = null;
        List<ContractUsageDto> response = api.contractUsageGetAll(greaterThanValue, numberToRead, skipRecords, lastModifiedDateTime, lastModifiedDateTimeCondition);

        // TODO: test validations
    }
    
    /**
     * Get a specific Contract Usage
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void contractUsageGetSpecificBycontractIdTest() {
        String contractId = null;
        ContractUsageDto response = api.contractUsageGetSpecificBycontractId(contractId);

        // TODO: test validations
    }
    
    /**
     * Update a specific Contract Usage
     *
     * Response Message has StatusCode NoContent if PUT operation succeed
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void contractUsagePutBycontractIdTest() {
        String contractId = null;
        ContractUsageUpdateDto contractUsage = null;
        Object response = api.contractUsagePutBycontractId(contractId, contractUsage);

        // TODO: test validations
    }
    
}
