/*
 * Visma Net API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.13.03.0008
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package no.systema.visma.v1client.api;

import no.systema.visma.v1client.model.GeneralLedgerBalanceDto;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for GeneralLedgerBalanceApi
 */
@Ignore
public class GeneralLedgerBalanceApiTest {

    private final GeneralLedgerBalanceApi api = new GeneralLedgerBalanceApi();

    
    /**
     * Get a range of General Ledger Balances
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void generalLedgerBalanceGetAllTest() {
        String greaterThanValue = null;
        Integer numberToRead = null;
        Integer skipRecords = null;
        String periodId = null;
        String periodIdCondition = null;
        String orderBy = null;
        String accountId = null;
        Integer yearClosed = null;
        String balanceType = null;
        Integer toggleBalanceSigns = null;
        Integer pageNumber = null;
        Integer pageSize = null;
        List<GeneralLedgerBalanceDto> response = api.generalLedgerBalanceGetAll(greaterThanValue, numberToRead, skipRecords, periodId, periodIdCondition, orderBy, accountId, yearClosed, balanceType, toggleBalanceSigns, pageNumber, pageSize);

        // TODO: test validations
    }
    
}
