/*
 * Visma Net API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.13.03.0008
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package no.systema.visma.v1client.api;

import no.systema.visma.v1client.model.PurchaseReceiptDto;
import no.systema.visma.v1client.model.PurchaseReceiptUpdateDto;
import no.systema.visma.v1client.model.ReleasePurchaseReceiptActionResultDto;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PurchaseReceiptApi
 */
@Ignore
public class PurchaseReceiptApiTest {

    private final PurchaseReceiptApi api = new PurchaseReceiptApi();

    
    /**
     * Get a range of Purchase Receipts
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void purchaseReceiptGetAllReceiptBasicTest() {
        String receiptType = null;
        String greaterThanValue = null;
        Integer numberToRead = null;
        Integer skipRecords = null;
        String lastModifiedDateTime = null;
        String lastModifiedDateTimeCondition = null;
        List<PurchaseReceiptDto> response = api.purchaseReceiptGetAllReceiptBasic(receiptType, greaterThanValue, numberToRead, skipRecords, lastModifiedDateTime, lastModifiedDateTimeCondition);

        // TODO: test validations
    }
    
    /**
     * Get a specific Purchase Receipt
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void purchaseReceiptGetPurchaseReceiptBasicByreceiptNbrTest() {
        String receiptNbr = null;
        PurchaseReceiptDto response = api.purchaseReceiptGetPurchaseReceiptBasicByreceiptNbr(receiptNbr);

        // TODO: test validations
    }
    
    /**
     * Create a Purchase Receipt
     *
     * Response Message has StatusCode Created if POST operation succeed
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void purchaseReceiptPostTest() {
        PurchaseReceiptUpdateDto poReceiptUpdateDto = null;
        Object response = api.purchaseReceiptPost(poReceiptUpdateDto);

        // TODO: test validations
    }
    
    /**
     * Get the print report of a Purchase Receipt
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void purchaseReceiptPrintPurchaseReceiptByreceiptNbrTest() {
        String receiptNbr = null;
        Object response = api.purchaseReceiptPrintPurchaseReceiptByreceiptNbr(receiptNbr);

        // TODO: test validations
    }
    
    /**
     * Update a specific Purchase Receipt
     *
     * Response Message has StatusCode NoContent if PUT operation succeed
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void purchaseReceiptPutBypoReceiptNumberTest() {
        String poReceiptNumber = null;
        PurchaseReceiptUpdateDto poReceiptUpdateDto = null;
        Object response = api.purchaseReceiptPutBypoReceiptNumber(poReceiptNumber, poReceiptUpdateDto);

        // TODO: test validations
    }
    
    /**
     * Release purchase receipt operation
     *
     * The action result dto contains information about the result of running the action
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void purchaseReceiptReleaseInvoiceByreceiptNumberTest() {
        String receiptNumber = null;
        ReleasePurchaseReceiptActionResultDto response = api.purchaseReceiptReleaseInvoiceByreceiptNumber(receiptNumber);

        // TODO: test validations
    }
    
}
