/*
 * Visma Net API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.13.03.0008
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package no.systema.visma.v1client.api;

import no.systema.visma.v1client.model.SalesOrderTypeDto;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SalesOrderTypeApi
 */
@Ignore
public class SalesOrderTypeApiTest {

    private final SalesOrderTypeApi api = new SalesOrderTypeApi();

    
    /**
     * Get a range of SO OrderTypes
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void salesOrderTypeGetAllSalesOrderTypesTest() {
        Integer numberToRead = null;
        Integer skipRecords = null;
        String orderBy = null;
        String lastModifiedDateTime = null;
        String lastModifiedDateTimeCondition = null;
        List<SalesOrderTypeDto> response = api.salesOrderTypeGetAllSalesOrderTypes(numberToRead, skipRecords, orderBy, lastModifiedDateTime, lastModifiedDateTimeCondition);

        // TODO: test validations
    }
    
    /**
     * Get a specific SO OrderType
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void salesOrderTypeGetSalesOrderTypeByorderTypeTest() {
        String orderType = null;
        SalesOrderTypeDto response = api.salesOrderTypeGetSalesOrderTypeByorderType(orderType);

        // TODO: test validations
    }
    
}
